<?php
/**
 * @file
 * Module file for starting drupal dev
 */

/**
 * Implementation of hook_menu().
 */

function monotool_menu() {

    $items['hello'] = array(
      'title' => 'Hello Menu',
      'type' => MENU_CALLBACK,
      'page callback' => 'hello_page_callback',
      'access callback' => TRUE,
    );

    return $items;

}

/*
 * Returns custom content to Drupal
 */
function hello_page_callback() {

    return theme('my_custom_template'); // Call theme() function, so that Drupal includes the custom-page.tpl.php template
}

/*
 * Implementation of hook_theme().
 */
function monotool_theme($existing, $type, $theme, $path){
    return array(
      'my_custom_template' => array(
        'template' => 'custom-page', // template file name will be custom-page.tpl.php
      ),
    );
}