<?php
/**
 * @file
 * Module file for starting drupal dev
 */

/**
 * Implementation of hook_menu().
 */


//Creating sub menu in the navigation bar

function monotool_menu() {

  $items['hello'] = array(
    'title' => 'Hello Menu',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'hello_page_callback',
    'access callback' => TRUE,
  );

  return $items;

}

function hello_page_callback() {

  $content['raw_markup'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Hello forld</p>',
  );

  return $content;

}

